### ISSUE TITLE
Issue when building

### ISSUE THREAD

**Issue by rlex** [thannaske/telegraf-teamspeak3#1]
Hello, it seems current master doesn't build (or i'm missing something):
```
./teamspeak.go:35:32: c.Server.ExtendedList undefined (type *ts3.ServerMethods has no field or method ExtendedList)
```

**Comment by thannaske** [comment]
Hey,

indeed you are not missing anything; this was my mistake.
I provided the main repository of `ts3-go` as dependency which has not implemented my pull request adding the `ExtendedList` method, yet. So I created a temporary fix by using my fork as library. 

Just execute `go get github.com/thannaske/go-ts3` and you should be good to "go" ;-)

**Comment by rlex** [comment]
Nice, will try it later.
P.S. any chances you will transform this [exec] plugin to actual telegraf input plugin?

**Comment by thannaske** [comment]
This will be the next step for me. First of all I decided to publish it like this as I guess that the process of the PR to telegraf could take a while.

**Comment by rlex** [comment]
Yup, thanks, compiled. However i'm getting [Error] Could not iterate through Teamspeak 3 server instances while trying to get metrics.

**Comment by rlex** [comment]
ok, i think i know why it happened.
```
builder@midgard:~/telegraf-teamspeak3$ telnet localhost 10011
Trying 127.0.0.1...
Connected to localhost.localdomain.
Escape character is '^]'.
TS3
Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.
help
error id=3329 msg=connection\sfailed,\syou\sare\sbanned extra_msg=you\smay\sretry\sin\s518\sseconds
```
Looks like it doesn't handle error message, maybe it's worth showing it in logs?

**Comment by thannaske** [comment]
Okay to reproduce that error I need a few more information from you.

Which Teamspeak 3 Version your server is running on? Has the query user sufficient rights to execute the following commands on **each** virtual server instance: `serverlist` and `serverinfo`?

Are you able to execute the following commands on Server Query CLI directly: 
`serverlist`
`use $sid`
`serverinfo`

(Replace $sid with the server ID you found for a  virtual server instance)

Thank you!

**Comment by rlex** [comment]
It's actually easy to reproduce, just knock to your server with wrong password several times. 

Version is 3.0.13.8

**Comment by thannaske** [comment]
> Looks like it doesn't handle error message, maybe it's worth showing it in logs?

Yes, I think it's worth it. I will address this issue in the go-ts3 library and add an error handler for this as soon as I got the ban-detection into the main code repository.

I close this issue as I guess that all problems are resolved at this moment.

**Comment by rlex** [comment]
Yup, works as intented now. Thanks!

**Comment by SkeeveAN** [comment]
The Problem is still there.

```
[root]# ll
-rw-r--r-- 1 root root 43245 18. Sep 07:25 grafana-dashboard.json
-rw-r--r-- 1 root root  1072 18. Sep 07:25 LICENSE
-rw-r--r-- 1 root root  3357 18. Sep 07:25 README.md
-rw-r--r-- 1 root root  3057 18. Sep 07:32 teamspeak.go
[root]# go build
# github.com/thannaske/telegraf-teamspeak3
./teamspeak.go:35:32: c.Server.ExtendedList undefined (type *ts3.ServerMethods has no field or method ExtendedList)
```

I used the current go-ts3 and I tried yours .. but still the same error

**Comment by thannaske** [comment]
Sorry to hear that you still encounter the issue. However this project is now longer actively maintenanced by me.
